"""add table of project module

Revision ID: 0177b4dc1909
Revises: a96dab496309
Create Date: 2025-08-06 17:27:04.204607

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0177b4dc1909"
down_revision: Union[str, None] = "a96dab496309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tbl_projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("update_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_project", sa.String(length=100), nullable=True),
        sa.Column("status_data", sa.String(length=100), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("commission_policy", sa.Text(), nullable=True),
        sa.Column("reward_policy", sa.Text(), nullable=True),
        sa.Column("other_policy", sa.Text(), nullable=True),
        sa.Column("withdrawal_status", sa.String(length=100), nullable=True),
        sa.Column("traffic_info", sa.Text(), nullable=True),
        sa.Column("evaluation_reason", sa.Text(), nullable=True),
        sa.Column("score_pre_run_check", sa.Text(), nullable=True),
        sa.Column("run_approval", sa.String(length=50), nullable=True),
        sa.Column("leader_note", sa.Text(), nullable=True),
        sa.Column("score_post_test_run_summary", sa.Text(), nullable=True),
        sa.Column("run_level", sa.DECIMAL(precision=3, scale=1), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("type_import_project", sa.String(length=255), nullable=True),
        sa.Column("id_ai_extracted_project", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_project_status_staff",
        "tbl_projects",
        ["status_project", "project_staff_id"],
        unique=False,
    )
    op.create_index(
        "idx_project_update_date_status",
        "tbl_projects",
        ["update_date", "status_project"],
        unique=False,
    )
    op.create_index(op.f("ix_tbl_projects_id"), "tbl_projects", ["id"], unique=False)
    op.create_index(op.f("ix_tbl_projects_name"), "tbl_projects", ["name"], unique=True)
    op.create_index(
        op.f("ix_tbl_projects_run_approval"),
        "tbl_projects",
        ["run_approval"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_projects_start_date"), "tbl_projects", ["start_date"], unique=False
    )
    op.create_index(
        op.f("ix_tbl_projects_status_data"),
        "tbl_projects",
        ["status_data"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_projects_status_project"),
        "tbl_projects",
        ["status_project"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_projects_type_import_project"),
        "tbl_projects",
        ["type_import_project"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_projects_update_date"),
        "tbl_projects",
        ["update_date"],
        unique=False,
    )
    op.create_index(op.f("ix_tbl_projects_url"), "tbl_projects", ["url"], unique=False)
    op.create_index(
        op.f("ix_tbl_projects_withdrawal_status"),
        "tbl_projects",
        ["withdrawal_status"],
        unique=False,
    )
    op.create_table(
        "tbl_project_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("login_url", sa.String(length=2048), nullable=True),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.Column("digital_staff_id", sa.UUID(), nullable=True),
        sa.Column("email_name", sa.String(length=255), nullable=True),
        sa.Column("email_password", sa.String(length=255), nullable=True),
        sa.Column("email_recovery", sa.String(length=255), nullable=True),
        sa.Column("email_2fa_key", sa.Text(), nullable=True),
        sa.Column("platform_username", sa.String(length=255), nullable=True),
        sa.Column("platform_password", sa.String(length=255), nullable=True),
        sa.Column("ref_link", sa.String(length=2048), nullable=True),
        sa.Column("vps_proxy_info", sa.Text(), nullable=True),
        sa.Column("digital_status", sa.String(length=100), nullable=True),
        sa.Column("payment_method", sa.Text(), nullable=True),
        sa.Column("two_fa_key", sa.Text(), nullable=True),
        sa.Column("kyc_status", sa.String(length=50), nullable=True),
        sa.Column("project_note", sa.Text(), nullable=True),
        sa.Column(
            "link_shared_date_to_staff", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("digital_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["tbl_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "account_name"),
    )
    op.create_index(
        op.f("ix_tbl_project_accounts_id"), "tbl_project_accounts", ["id"], unique=False
    )
    op.create_table(
        "tbl_project_history",
        sa.Column("history_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_project", sa.String(length=100), nullable=True),
        sa.Column("status_data", sa.String(length=100), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("commission_policy", sa.Text(), nullable=True),
        sa.Column("reward_policy", sa.Text(), nullable=True),
        sa.Column("other_policy", sa.Text(), nullable=True),
        sa.Column("withdrawal_status", sa.String(length=100), nullable=True),
        sa.Column("traffic_info", sa.Text(), nullable=True),
        sa.Column("evaluation_reason", sa.Text(), nullable=True),
        sa.Column("score_pre_run_check", sa.Text(), nullable=True),
        sa.Column("run_approval", sa.String(length=50), nullable=True),
        sa.Column("leader_note", sa.Text(), nullable=True),
        sa.Column("score_post_test_run_summary", sa.Text(), nullable=True),
        sa.Column("run_level", sa.DECIMAL(precision=3, scale=1), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("type_import_project", sa.String(length=255), nullable=True),
        sa.Column("id_ai_extracted_project", sa.String(length=255), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("history_action", sa.String(length=10), nullable=False),
        sa.Column("history_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["tbl_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_index(
        op.f("ix_tbl_project_history_history_id"),
        "tbl_project_history",
        ["history_id"],
        unique=False,
    )
    op.create_table(
        "tbl_project_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("assigned_to_staff_id", sa.UUID(), nullable=True),
        sa.Column("created_by_staff_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["tbl_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_project_tasks_id"), "tbl_project_tasks", ["id"], unique=False
    )
    op.create_table(
        "tbl_ads_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("project_staff_id", sa.UUID(), nullable=False),
        sa.Column("project_account_id", sa.UUID(), nullable=False),
        sa.Column("action_type", sa.String(length=100), nullable=True),
        sa.Column("sales_amount", sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column("ref_code", sa.String(length=100), nullable=True),
        sa.Column("withdrawal_info", sa.Text(), nullable=True),
        sa.Column("monthly_sales", sa.DECIMAL(precision=15, scale=2), nullable=True),
        sa.Column("sales_channel", sa.String(length=100), nullable=True),
        sa.Column("receiving_wallet", sa.String(length=255), nullable=True),
        sa.Column("transaction_history", sa.Text(), nullable=True),
        sa.Column("transaction_image_url", sa.String(length=2048), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_account_id"],
            ["tbl_project_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_ads_reports_id"), "tbl_ads_reports", ["id"], unique=False
    )
    op.create_table(
        "tbl_withdrawal_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_account_id", sa.UUID(), nullable=False),
        sa.Column("created_by_staff_id", sa.UUID(), nullable=False),
        sa.Column("request_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_account_id"],
            ["tbl_project_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_withdrawal_plans_id"), "tbl_withdrawal_plans", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tbl_withdrawal_plans_id"), table_name="tbl_withdrawal_plans")
    op.drop_table("tbl_withdrawal_plans")
    op.drop_index(op.f("ix_tbl_ads_reports_id"), table_name="tbl_ads_reports")
    op.drop_table("tbl_ads_reports")
    op.drop_index(op.f("ix_tbl_project_tasks_id"), table_name="tbl_project_tasks")
    op.drop_table("tbl_project_tasks")
    op.drop_index(
        op.f("ix_tbl_project_history_history_id"), table_name="tbl_project_history"
    )
    op.drop_table("tbl_project_history")
    op.drop_index(op.f("ix_tbl_project_accounts_id"), table_name="tbl_project_accounts")
    op.drop_table("tbl_project_accounts")
    op.drop_index(op.f("ix_tbl_projects_withdrawal_status"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_url"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_update_date"), table_name="tbl_projects")
    op.drop_index(
        op.f("ix_tbl_projects_type_import_project"), table_name="tbl_projects"
    )
    op.drop_index(op.f("ix_tbl_projects_status_project"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_status_data"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_start_date"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_run_approval"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_name"), table_name="tbl_projects")
    op.drop_index(op.f("ix_tbl_projects_id"), table_name="tbl_projects")
    op.drop_index("idx_project_update_date_status", table_name="tbl_projects")
    op.drop_index("idx_project_status_staff", table_name="tbl_projects")
    op.drop_table("tbl_projects")
    # ### end Alembic commands ###
