"""add_enum_not_started

Revision ID: 074f77ff00cd
Revises: 65ba577b55c8
Create Date: 2025-08-06 10:39:04.461296

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "074f77ff00cd"
down_revision: Union[str, None] = "65ba577b55c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE keywordstatusrun ADD VALUE 'NOTSTARTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
