"""check

Revision ID: 0accd1a5607f
Revises: 0177b4dc1909
Create Date: 2025-09-05 13:39:20.055351

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0accd1a5607f"
down_revision: Union[str, None] = "0177b4dc1909"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tbl_keywords",
        "list_sub_niche_id",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tbl_keywords",
        "list_sub_niche_id",
        existing_type=postgresql.ARRAY(sa.UUID()),
        nullable=True,
    )
    # ### end Alembic commands ###
