"""remove_relation_history_keyword

Revision ID: 21543f7d6e7b
Revises: 074f77ff00cd
Create Date: 2025-08-06 11:11:47.694019

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21543f7d6e7b"
down_revision: Union[str, None] = "074f77ff00cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "tbl_keyword_histories_keyword_id_fkey",
        "tbl_keyword_histories",
        type_="foreignkey",
    )
    op.drop_constraint(
        "tbl_keyword_history_search_keyword_id_fkey",
        "tbl_keyword_history_search",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "tbl_keyword_history_search_keyword_id_fkey",
        "tbl_keyword_history_search",
        "tbl_keywords",
        ["keyword_id"],
        ["id"],
    )
    op.create_foreign_key(
        "tbl_keyword_histories_keyword_id_fkey",
        "tbl_keyword_histories",
        "tbl_keywords",
        ["keyword_id"],
        ["id"],
    )
    # ### end Alembic commands ###
