"""change name niche and subniche not unique

Revision ID: 768e0393c950
Revises: 32c38d5c0415
Create Date: 2025-08-05 17:09:54.022823

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "768e0393c950"
down_revision: Union[str, None] = "32c38d5c0415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tbl_niches_name_key", "tbl_niches", type_="unique")
    op.drop_constraint("tbl_subniches_name_key", "tbl_subniches", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("tbl_subniches_name_key", "tbl_subniches", ["name"])
    op.create_unique_constraint("tbl_niches_name_key", "tbl_niches", ["name"])
    # ### end Alembic commands ###
