"""start db

Revision ID: 9d52a8abee5b
Revises: 
Create Date: 2025-09-26 10:33:13.220138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d52a8abee5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_is_active'), 'agents', ['is_active'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_index(op.f('ix_agents_version'), 'agents', ['version'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_created_at'), 'tools', ['created_at'], unique=False)
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_is_active'), 'tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_agent_id', 'conversations', ['agent_id'], unique=False)
    op.create_index('idx_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_is_active'), 'conversations', ['is_active'], unique=False)
    op.create_index(op.f('ix_conversations_title'), 'conversations', ['title'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='domains_user_name_uk')
    )
    op.create_index('idx_domains_user_id', 'domains', ['user_id'], unique=False)
    op.create_index(op.f('ix_domains_created_at'), 'domains', ['created_at'], unique=False)
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_is_active'), 'domains', ['is_active'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=False)
    op.create_index(op.f('ix_domains_updated_at'), 'domains', ['updated_at'], unique=False)
    op.create_index(op.f('ix_domains_user_id'), 'domains', ['user_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"index" >= 0', name='conversation_summaries_idx_ck'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'index', name='conversation_summaries_conv_idx_uk')
    )
    op.create_index('idx_conversation_summaries_conversation_id', 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_conversation_id'), 'conversation_summaries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_created_at'), 'conversation_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_index'), 'conversation_summaries', ['index'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_updated_at'), 'conversation_summaries', ['updated_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('list_agent_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('"index" >= 0', name='messages_idx_ck'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'index', name='messages_conv_idx_uk')
    )
    op.create_index('idx_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_index'), 'messages', ['index'], unique=False)
    op.create_table('subdomains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'name', name='subdomains_domain_name_uk')
    )
    op.create_index('idx_subdomains_domain_id', 'subdomains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_subdomains_created_at'), 'subdomains', ['created_at'], unique=False)
    op.create_index(op.f('ix_subdomains_domain_id'), 'subdomains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_subdomains_id'), 'subdomains', ['id'], unique=False)
    op.create_index(op.f('ix_subdomains_is_active'), 'subdomains', ['is_active'], unique=False)
    op.create_index(op.f('ix_subdomains_name'), 'subdomains', ['name'], unique=False)
    op.create_index(op.f('ix_subdomains_updated_at'), 'subdomains', ['updated_at'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('step_retry', sa.Integer(), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('step >= 1', name='agent_steps_step_ck'),
    sa.CheckConstraint('step_retry >= 0', name='agent_steps_step_retry_ck'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'step', name='agent_steps_msg_step_uk')
    )
    op.create_index('idx_agent_steps_agent_id', 'agent_steps', ['agent_id'], unique=False)
    op.create_index('idx_agent_steps_message_id', 'agent_steps', ['message_id'], unique=False)
    op.create_index('idx_agent_steps_tool_id', 'agent_steps', ['tool_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_agent_id'), 'agent_steps', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_created_at'), 'agent_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_steps_id'), 'agent_steps', ['id'], unique=False)
    op.create_index(op.f('ix_agent_steps_message_id'), 'agent_steps', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_step'), 'agent_steps', ['step'], unique=False)
    op.create_index(op.f('ix_agent_steps_step_retry'), 'agent_steps', ['step_retry'], unique=False)
    op.create_index(op.f('ix_agent_steps_tool_id'), 'agent_steps', ['tool_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subdomain_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', name='documents_path_uk'),
    sa.UniqueConstraint('subdomain_id', 'name', name='documents_subdomain_name_uk')
    )
    op.create_index('idx_documents_subdomain_id', 'documents', ['subdomain_id'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_file_type'), 'documents', ['file_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_index(op.f('ix_documents_path'), 'documents', ['path'], unique=False)
    op.create_index(op.f('ix_documents_subdomain_id'), 'documents', ['subdomain_id'], unique=False)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='document_chunks_chunkidx_ck'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunks_doc_chunkidx_uk')
    )
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_chunk_index'), 'document_chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_created_at'), 'document_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_created_at'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_index'), table_name='document_chunks')
    op.drop_index('idx_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_subdomain_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_path'), table_name='documents')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index('idx_documents_subdomain_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_agent_steps_tool_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_step_retry'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_step'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_message_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_created_at'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_id'), table_name='agent_steps')
    op.drop_index('idx_agent_steps_tool_id', table_name='agent_steps')
    op.drop_index('idx_agent_steps_message_id', table_name='agent_steps')
    op.drop_index('idx_agent_steps_agent_id', table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_subdomains_updated_at'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_name'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_is_active'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_id'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_domain_id'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_created_at'), table_name='subdomains')
    op.drop_index('idx_subdomains_domain_id', table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index(op.f('ix_messages_index'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_summaries_updated_at'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_index'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_created_at'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_conversation_id'), table_name='conversation_summaries')
    op.drop_index('idx_conversation_summaries_conversation_id', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_domains_user_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_updated_at'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_is_active'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_created_at'), table_name='domains')
    op.drop_index('idx_domains_user_id', table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_title'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_is_active'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_index('idx_conversations_user_id', table_name='conversations')
    op.drop_index('idx_conversations_agent_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_is_active'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_created_at'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_agents_version'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_is_active'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###