"""create keywords table

Revision ID: c6c2a371b1ea
Revises:
Create Date: 2025-08-04 16:01:10.426306

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6c2a371b1ea"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tbl_domains",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tbl_domains_id"), "tbl_domains", ["id"], unique=False)
    op.create_table(
        "tbl_niches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["tbl_domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tbl_niches_id"), "tbl_niches", ["id"], unique=False)
    op.create_table(
        "tbl_subniches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("niche_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["niche_id"],
            ["tbl_niches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tbl_subniches_id"), "tbl_subniches", ["id"], unique=False)
    op.create_table(
        "tbl_keywords",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prefix", sa.String(length=255), nullable=True),
        sa.Column("main_keyword", sa.String(length=255), nullable=False),
        sa.Column("suffix", sa.String(length=255), nullable=True),
        sa.Column("full_keyword", sa.String(length=1024), nullable=False),
        sa.Column("scan_platform", sa.String(length=100), nullable=True),
        sa.Column("total_links_scanned", sa.Integer(), nullable=False),
        sa.Column("total_links_new", sa.Integer(), nullable=False),
        sa.Column("total_links_dupicate", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DEACTIVATED", name="keywordstatus"),
            nullable=False,
        ),
        sa.Column(
            "status_run",
            sa.Enum("RUNNING", "ERROR", "SUCCESS", name="keywordstatusrun"),
            nullable=False,
        ),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("scheduler_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("niche_id", sa.UUID(), nullable=False),
        sa.Column("sub_niche_id", sa.UUID(), nullable=True),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["tbl_domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["niche_id"],
            ["tbl_niches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_niche_id"],
            ["tbl_subniches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_keyword"),
    )
    op.create_index(op.f("ix_tbl_keywords_id"), "tbl_keywords", ["id"], unique=False)
    op.create_table(
        "tbl_keyword_histories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("history_action", sa.String(length=50), nullable=False),
        sa.Column("history_timestamp", sa.DateTime(), nullable=False),
        sa.Column("keyword_id", sa.UUID(), nullable=False),
        sa.Column("prefix", sa.String(length=255), nullable=True),
        sa.Column("main_keyword", sa.String(length=255), nullable=False),
        sa.Column("suffix", sa.String(length=255), nullable=True),
        sa.Column("scan_platform", sa.String(length=100), nullable=True),
        sa.Column("total_links_scanned", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DEACTIVATED", name="keywordstatus"),
            nullable=True,
        ),
        sa.Column("favorite", sa.Boolean(), nullable=True),
        sa.Column("scheduler_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("niche_id", sa.UUID(), nullable=False),
        sa.Column("sub_niche_id", sa.UUID(), nullable=True),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["tbl_keywords.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_keyword_histories_id"),
        "tbl_keyword_histories",
        ["id"],
        unique=False,
    )
    op.create_table(
        "tbl_keyword_history_search",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("search_results", sa.JSON(), nullable=False),
        sa.Column("search_date", sa.DateTime(), nullable=False),
        sa.Column("total_link_search", sa.Integer(), nullable=False),
        sa.Column("total_link_search_new", sa.Integer(), nullable=False),
        sa.Column("total_link_search_dup", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.UUID(), nullable=False),
        sa.Column("project_staff_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["tbl_keywords.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_keyword_history_search_id"),
        "tbl_keyword_history_search",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tbl_keyword_history_search_id"),
        table_name="tbl_keyword_history_search",
    )
    op.drop_table("tbl_keyword_history_search")
    op.drop_index(
        op.f("ix_tbl_keyword_histories_id"), table_name="tbl_keyword_histories"
    )
    op.drop_table("tbl_keyword_histories")
    op.drop_index(op.f("ix_tbl_keywords_id"), table_name="tbl_keywords")
    op.drop_table("tbl_keywords")
    op.drop_index(op.f("ix_tbl_subniches_id"), table_name="tbl_subniches")
    op.drop_table("tbl_subniches")
    op.drop_index(op.f("ix_tbl_niches_id"), table_name="tbl_niches")
    op.drop_table("tbl_niches")
    op.drop_index(op.f("ix_tbl_domains_id"), table_name="tbl_domains")
    op.drop_table("tbl_domains")
    # ### end Alembic commands ###
